db:
  image: postgres
  volumes:
    - /var/lib/cabotdb:/var/lib/postgresql
  environment:
    POSTGRES_USER: docker
    POSTGRES_DB: docker
    POSTGRES_PASSWORD: docker
  ports:
    - "5432:5432" #pgsql

celery_broker:
  image: redis
  expose:
    - "6394:6394"
  ports:
    - "6394:6394" #redis
  volumes:
     - ./redis/redis.conf:/etc/redis/redis.conf:ro
     - /etc/redis
  command: redis-server /etc/redis/redis.conf

cabot:
  build: ./cabot
  links:
    - db
    - celery_broker
    - grafana-graphite
    # - smtp_server
  volumes:
    - /cabot
  env_file: cabot_env
  ports:
    - "5000:5000"

grafana-graphite:
  build: ./grafana-graphite
  volumes:
    - /grafana-graphite
  expose:
    - "8000:8000" #graphite
  ports:
    - "3000:3000" #grafana
    - "8000:8000" #graphite
    - "8126:8126" #statsd admin
    - "8125:8125/udp" #statsd udp

smtp_server:
  image: tianon/exim4
  ports:
    - "25:25"

nginx:
  image: nginx
  ports:
     - "80:80" #nginx
     - "81:81" #graphite-web
     - "8080:8080" #cabot
  links:
     - cabot:cabot
     - grafana-graphite:grafana-graphite
  volumes_from:
     - cabot
     - grafana-graphite
  volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - /var/log/
  command: /etc/init.d/nginx start